-- Enable Row Level Security (RLS) is enabled by default on new tables in Supabase, but we explicity enable it.

-- DROP TABLES cleanup to ensure schema updates (like new columns) are applied
DROP TABLE IF EXISTS experience, projects, education, skills, profiles CASCADE;

-- 1. PROFILES TABLE (Single record for main user info)
create table if not exists profiles (
  id uuid references auth.users on delete cascade primary key,
  name text not null,
  role text,
  address text,
  phone text,
  email text,
  nationality text,
  summary text,
  social_linkedin text,
  social_github text,
  social_portfolio text,
  resume_url text,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles for select using ( true );
create policy "Users can insert their own profile." on profiles for insert with check ( auth.uid() = id );
create policy "Users can update own profile." on profiles for update using ( auth.uid() = id );

-- 2. EXPERIENCE TABLE (Enhanced)
create table if not exists experience (
  id bigint generated by default as identity primary key,
  company text not null,
  position text not null,
  location text,
  description text,
  duration text,
  is_development boolean default true,
  start_date date,
  end_date date,
  type text, -- Full-time, Internship, Freelance, Part-time
  skills text[], -- Array of skills used
  logo_url text, -- For company logo
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table experience enable row level security;

create policy "Experience viewable by everyone." on experience for select using ( true );
create policy "Experience insertable by authenticated." on experience for insert with check ( auth.role() = 'authenticated' );
create policy "Experience updatable by authenticated." on experience for update using ( auth.role() = 'authenticated' );
create policy "Experience deletable by authenticated." on experience for delete using ( auth.role() = 'authenticated' );

-- 3. PROJECTS TABLE
create table if not exists projects (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  tech text[], -- Array of strings
  github_url text,
  live_url text,
  featured boolean default false,
  year text,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table projects enable row level security;

create policy "Projects viewable by everyone." on projects for select using ( true );
create policy "Projects insertable by authenticated." on projects for insert with check ( auth.role() = 'authenticated' );
create policy "Projects updatable by authenticated." on projects for update using ( auth.role() = 'authenticated' );
create policy "Projects deletable by authenticated." on projects for delete using ( auth.role() = 'authenticated' );

-- 4. EDUCATION TABLE
create table if not exists education (
  id bigint generated by default as identity primary key,
  degree text not null,
  university text not null,
  period text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table education enable row level security;

create policy "Education viewable by everyone." on education for select using ( true );
create policy "Education insertable by authenticated." on education for insert with check ( auth.role() = 'authenticated' );
create policy "Education updatable by authenticated." on education for update using ( auth.role() = 'authenticated' );
create policy "Education deletable by authenticated." on education for delete using ( auth.role() = 'authenticated' );

-- 5. SKILLS TABLE
create table if not exists skills (
  id bigint generated by default as identity primary key,
  category text not null, -- e.g. "Languages", "Frameworks"
  items text[], -- Array of strings
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table skills enable row level security;

create policy "Skills viewable by everyone." on skills for select using ( true );
create policy "Skills insertable by authenticated." on skills for insert with check ( auth.role() = 'authenticated' );
create policy "Skills updatable by authenticated." on skills for update using ( auth.role() = 'authenticated' );
create policy "Skills deletable by authenticated." on skills for delete using ( auth.role() = 'authenticated' );


-- INITIAL DATA INSERTION (Updated with new experience data)

-- Clear existing data to avoid duplicates if re-running
TRUNCATE TABLE experience RESTART IDENTITY;
TRUNCATE TABLE projects RESTART IDENTITY;
TRUNCATE TABLE education RESTART IDENTITY;
TRUNCATE TABLE skills RESTART IDENTITY;

-- Insert Experience
INSERT INTO experience (company, position, location, type, duration, skills, description, is_development) VALUES
('Devsinc', 'Software Engineer Intern', 'Lahore, Pakistan', 'Internship', 'Aug 2026 - Present',
 ARRAY['AWS', 'GitHub Actions', 'CI/CD', 'REST APIs'],
 'Contributing to Agents Anywhere, an applied AI platform that helps mid-market and enterprise companies turn their knowledge into AI tools, agents and automated workflows, with human approval on sensitive actions. Built the client intake framework and dossier generation, connectors, plugins, MCP skills and Orbit features, and set up AWS deployment with GitHub Actions CI/CD. Also contributing to VeriCasa, an AI-powered legal-tech platform for real estate agencies, law firms and notaries in the Portuguese and US markets, running 100+ automated legal cross-checks and generating contracts in seconds. Developed full-stack features across document analysis, contract generation and KYC compliance workflows, with REST APIs, encrypted document storage and GDPR-compliant data handling.',
 true),

('Directorate of Information Technology, GCU', 'Junior Software Developer', 'Lahore, Pakistan', 'Full-time', 'May 2025 - May 2026',
 ARRAY['Angular', 'Node.js', 'Express', 'MySQL'],
 'Contributed to core modules of the university LMS, serving 10,000+ students, faculty and staff, using Angular, Node.js, Express and MySQL. Built the Summer Enrollment Module, automating registration for about 1,000 students per cycle, the Teachers Billing Module, replacing a 3-month manual process for 1,000+ faculty, and the Teacher Evaluation Module. Contributed to attendance tracking, eligibility checks and grading with automated student progress reports, role-based access and PDF report generation. Built the GCU Societies Portal from scratch with 7-role access control, society registration, event approval, member management and society points tracking. Optimized MySQL queries and indexing on high-volume enrollment data. Developed the Student Scholarship and Student ID Card modules for the Student Facilitation Center, and reduced critical production bugs through manual SQA and regression testing.',
 true);

-- Insert Education
INSERT INTO education (degree, university, period) VALUES
('BS (Hons) in Computer Science', 'Government College University, Lahore', '2022 - 2026 · CGPA 3.14'),
('FSc Pre-Engineering', 'Punjab College of Science, Lahore', '2020 - 2022 · 961/1100');

-- Insert Skills
INSERT INTO skills (category, items) VALUES
('Languages', ARRAY['JavaScript (ES6+)', 'TypeScript', 'Python', 'C++', 'HTML5', 'CSS3']),
('Frontend', ARRAY['React.js', 'Next.js', 'Angular', 'Redux', 'Vite', 'Tailwind CSS', 'ShadCN UI', 'Radix UI', 'Responsive Design']),
('Backend', ARRAY['Node.js', 'Express.js', 'Django', 'Django REST Framework', 'FastAPI', 'REST API design', 'GraphQL', 'Rate Limiting']),
('Databases & ORM', ARRAY['MySQL', 'MongoDB', 'Redis', 'Prisma ORM', 'Mongoose', 'Schema Design', 'Query Optimization']),
('Auth & Realtime', ARRAY['JWT Authentication', 'Socket.io', 'Nodemailer', 'Multer', 'JSPDF']),
('Cloud & DevOps', ARRAY['AWS', 'Docker', 'CI/CD Pipelines', 'GitHub Actions']),
('Tools', ARRAY['Git & GitHub', 'Postman', 'VS Code', 'MySQL Workbench', 'MongoDB Compass']),
('Core Concepts', ARRAY['OOP', 'Data Structures & Algorithms', 'DBMS']),
('Practices', ARRAY['Manual SQA Testing', 'Agile/Scrum', 'Sprint Planning', 'Code Reviews', 'Role-Based Access Control']);

-- Insert Projects
INSERT INTO projects (name, description, tech, github_url, live_url, featured, year) VALUES
('Skill Bridge', 'AI-powered freelance marketplace with an autonomous hiring agent that turns a client''s idea into structured scope, budget, tech stack and timeline, then matches and ranks freelancers, negotiates, and generates the contract. Role-based access for client, freelancer and admin, with real-time chat, reviews, Stripe escrow, bidding, skill tokens and dispute resolution.', ARRAY['React', 'TypeScript', 'Node.js', 'Express', 'Prisma', 'MongoDB', 'Redis', 'Socket.IO', 'Stripe', 'FastAPI'], NULL, 'https://skillbridge.ddns.net', true, NULL),
('Health Connect', 'Multi-role healthcare management platform for admins, clinics, front desk staff and super admins. Appointment workflows, front desk management and billing, with role-based dashboards, REST APIs, Prisma, JWT authentication and a React frontend deployed on Vercel.', ARRAY['React', 'TypeScript', 'Vite', 'Node.js', 'Express', 'Prisma', 'MySQL'], NULL, 'https://health-connect-super.vercel.app', true, NULL),
('Lead Management System', 'CRM-style lead management engine that tracks sales leads through multi-phase technical evaluation to final sale conversion, with phase accept and decline workflows. Role-based access for Business Development, Technical Manager and Engineer, comments with image attachments, and automated commission calculation on converted sales.', ARRAY['Django', 'Django REST Framework', 'PostgreSQL', 'Django Templates', 'AJAX'], 'https://github.com/Daniyal00001/Leads-management-system', NULL, true, NULL),
('The College Periodical', 'Academic publishing platform where authors submit articles anonymously and publish them through peer review. Reviewer and Super Admin portals, JWT authentication, bcrypt password hashing, protected admin routes and email notifications, deployed on Vercel.', ARRAY['Next.js', 'React', 'Tailwind CSS', 'MySQL', 'JWT', 'Supabase', 'Nodemailer'], NULL, 'https://thecollegeperiodical.com', true, NULL);

-- 6. MESSAGES TABLE
create table if not exists messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table messages enable row level security;

create policy "Messages insertable by everyone." on messages for insert with check ( true );
create policy "Messages viewable by authenticated." on messages for select using ( auth.role() = 'authenticated' );
create policy "Messages updatable by authenticated." on messages for update using ( auth.role() = 'authenticated' );
create policy "Messages deletable by authenticated." on messages for delete using ( auth.role() = 'authenticated' );
