-- Contact form inbox. Safe to re-run if the table already exists.
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.messages enable row level security;

grant insert on table public.messages to anon, authenticated;
grant select, update, delete on table public.messages to authenticated;
grant all on table public.messages to service_role;

drop policy if exists "Messages insertable by everyone." on public.messages;
create policy "Messages insertable by everyone."
  on public.messages for insert
  with check (true);

drop policy if exists "Messages viewable by authenticated." on public.messages;
create policy "Messages viewable by authenticated."
  on public.messages for select
  using (auth.role() = 'authenticated');

drop policy if exists "Messages updatable by authenticated." on public.messages;
create policy "Messages updatable by authenticated."
  on public.messages for update
  using (auth.role() = 'authenticated');

drop policy if exists "Messages deletable by authenticated." on public.messages;
create policy "Messages deletable by authenticated."
  on public.messages for delete
  using (auth.role() = 'authenticated');

notify pgrst, 'reload schema';
